// Données de démonstration — utilisées uniquement en secours quand l'API
// (notre-voie-api) n'est pas joignable ou que la base n'est pas encore
// peuplée. Les formes (champs, relations) reproduisent exactement les
// réponses réelles de l'API pour que basculer sur les vraies données ne
// demande aucune modification de composant. Voir docs/DECISIONS.md.

export const RUBRIQUES = [
  { id: 'r1', slug: 'politique', nom: 'Politique', type: 'EDITORIALE', couleur: '#0B6FA8', ordre: 0 },
  { id: 'r2', slug: 'refondation', nom: 'Refondation', type: 'EDITORIALE', couleur: '#0E8FD6', ordre: 1 },
  { id: 'r3', slug: 'economie', nom: 'Économie', type: 'EDITORIALE', couleur: '#0B6FA8', ordre: 2 },
  { id: 'r4', slug: 'vie-chere', nom: 'Vie chère', type: 'EDITORIALE', couleur: '#E6008C', ordre: 3 },
  { id: 'r5', slug: 'societe', nom: 'Société', type: 'EDITORIALE', couleur: '#0B6FA8', ordre: 4 },
  { id: 'r6', slug: 'regions', nom: 'Régions', type: 'EDITORIALE', couleur: '#0B6FA8', ordre: 5 },
  { id: 'r7', slug: 'diaspora', nom: 'Diaspora', type: 'EDITORIALE', couleur: '#E8B84B', ordre: 6 },
  { id: 'r8', slug: 'culture', nom: 'Culture', type: 'EDITORIALE', couleur: '#E6008C', ordre: 7 },
  { id: 'r9', slug: 'sport', nom: 'Sport', type: 'EDITORIALE', couleur: '#0B6FA8', ordre: 8 },
  { id: 'r10', slug: 'verite-ou-intox', nom: 'Vérité ou Intox', type: 'EDITORIALE', couleur: '#E8B84B', ordre: 9 },
];

const r = (slug) => RUBRIQUES.find((x) => x.slug === slug);

function il(n) {
  return new Date(Date.now() - n * 60 * 1000).toISOString();
}

export const ARTICLES = [
  {
    id: 'a1',
    slug: 'refondation-suivi-reformes-institutionnelles-conseil-ministres',
    titre: "Réformes institutionnelles : ce que change le dernier Conseil des ministres",
    chapo: "Trois textes adoptés cette semaine touchent directement l'organisation des collectivités locales. Notre Voie décrypte leur portée concrète pour les citoyens.",
    contenuHtml: '<p>Le Conseil des ministres a adopté trois décrets d\'application qui précisent les modalités de mise en œuvre de la réforme des collectivités territoriales votée en début d\'année. Concrètement, ces textes fixent les compétences transférées aux mairies en matière de gestion foncière et de propreté urbaine.</p><p>Pour les administrés, le changement le plus visible concerne les délais de traitement des actes d\'état civil, désormais ramenés à 72 heures dans les communes pilotes. Notre Voie a interrogé plusieurs maires concernés, qui saluent une clarification attendue depuis plusieurs années.</p><p>La montée en charge sera progressive : une dizaine de communes sont concernées dans un premier temps, avant une généralisation prévue courant de l\'année prochaine.</p>',
    tags: ['réformes', 'collectivités', 'gouvernement'],
    format: 'DECRYPTAGE',
    statut: 'PUBLIE',
    paywall: 'PAYANT',
    imageUneUrl: null,
    dureeEcouteSec: 210,
    vuesTotal: 4820,
    publieLe: il(140),
    rubrique: r('refondation'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Koré', prenom: 'Benjamin' },
  },
  {
    id: 'a2',
    slug: 'vie-chere-ticker-hausse-prix-riz-aout',
    titre: 'Le prix du sac de riz importé repart à la hausse',
    chapo: "Après plusieurs semaines de stabilité, le sac de 50 kg franchit un nouveau seuil sur les marchés d'Abidjan. Notre Voie a fait le tour des grossistes.",
    contenuHtml: '<p>Sur le marché de gros de Bouaké comme sur celui d\'Adjamé, les grossistes constatent tous la même tendance depuis une dizaine de jours : le prix du riz importé augmente, tiré par la hausse du fret maritime.</p><p>Plusieurs commerçants interrogés par notre rédaction évoquent une hausse directement répercutée sur les détaillants, qui peinent à absorber la différence sans toucher leur marge.</p>',
    tags: ['riz', 'pouvoir d\'achat', 'marché'],
    format: 'EDITION',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: 95,
    vuesTotal: 12300,
    publieLe: il(320),
    rubrique: r('vie-chere'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Bédé', prenom: 'Charles' },
  },
  {
    id: 'a3',
    slug: 'flash-arrivee-delegation-cedeao-abidjan',
    titre: "Une délégation de la CEDEAO attendue à Abidjan cet après-midi",
    chapo: 'Information confirmée par le protocole d\'État il y a quelques minutes.',
    contenuHtml: '<p>Une délégation de haut niveau de la CEDEAO est attendue en fin d\'après-midi à l\'aéroport Félix Houphouët-Boigny. Notre Voie suit la situation et publiera un compte-rendu détaillé dans l\'édition de demain.</p>',
    tags: ['CEDEAO', 'diplomatie'],
    format: 'FLASH',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: 30,
    vuesTotal: 2100,
    publieLe: il(12),
    rubrique: r('politique'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Zébé', prenom: 'Arthur' },
  },
  {
    id: 'a4',
    slug: 'live-finale-championnat-ivoirien',
    titre: "Finale du championnat : suivez la rencontre minute par minute",
    chapo: "Notre Voie couvre en direct la grande finale de la Ligue 1 ivoirienne, disputée ce soir à Abidjan.",
    contenuHtml: '<p>Coup d\'envoi donné il y a quelques minutes. Notre équipe sur place vous tient informés en temps réel.</p>',
    tags: ['football', 'championnat ivoirien'],
    format: 'LIVE',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: null,
    vuesTotal: 8900,
    publieLe: il(38),
    rubrique: r('sport'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    liveUpdates: [
      { id: 'lu1', contenu: "45e minute : la première période s'achève sur un score nul et vierge.", horodatage: il(4) },
      { id: 'lu2', contenu: "23e minute : occasion nette côté visiteurs, la barre transversale sauve les locaux.", horodatage: il(20) },
      { id: 'lu3', contenu: "Coup d'envoi de la rencontre.", horodatage: il(38) },
    ],
    auteur: { nom: 'K.', prenom: 'Bruno' },
  },
  {
    id: 'a5',
    slug: 'verite-ou-intox-fausse-annonce-gratuite-carburant',
    titre: "Non, aucune distribution gratuite de carburant n'a été annoncée",
    chapo: 'Une publication largement partagée sur WhatsApp affirme le contraire. Voici ce qu\'il en est réellement.',
    contenuHtml: '<p>Un message vocal circule depuis hier soir sur WhatsApp, annonçant une distribution gratuite de carburant dans plusieurs stations d\'Abidjan à partir de demain. Aucune source officielle — ni le ministère du Pétrole, ni les compagnies pétrolières concernées — ne confirme cette information.</p><p>Notre Voie a contacté le service de communication du ministère, qui dément formellement toute annonce de ce type.</p>',
    tags: ['fact-check', 'carburant', 'rumeur'],
    format: 'VERITE_OU_INTOX',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: 60,
    vuesTotal: 15600,
    publieLe: il(200),
    rubrique: r('verite-ou-intox'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: {
      verdict: 'FAUX',
      rumeurOrigine: "Message vocal WhatsApp annonçant une distribution gratuite de carburant",
      sourceRumeur: 'WhatsApp',
      preuves: "Démenti du ministère du Pétrole, aucune source officielle ne confirme l'annonce.",
    },
    auteur: { nom: 'Tiony', prenom: 'Christian' },
  },
  {
    id: 'a6',
    slug: 'diaspora-nouvelles-modalites-transfert-argent',
    titre: 'Transferts d\'argent depuis la diaspora : ce qui change pour les frais',
    chapo: "Plusieurs opérateurs ajustent leurs grilles tarifaires ce mois-ci. Notre Voie compare les offres pour les Ivoiriens de l'étranger.",
    contenuHtml: '<p>Les Ivoiriens établis en Europe et en Amérique du Nord constateront une légère baisse des frais sur les transferts vers le pays via les principaux opérateurs de mobile money, à compter de ce mois-ci.</p>',
    tags: ['diaspora', 'mobile money'],
    format: 'EDITION',
    statut: 'PUBLIE',
    paywall: 'PAYANT',
    imageUneUrl: null,
    dureeEcouteSec: 130,
    vuesTotal: 3400,
    publieLe: il(500),
    rubrique: r('diaspora'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Ahouasso', prenom: 'Abigaëlle' },
  },
  {
    id: 'a7',
    slug: 'culture-nouchi-dictionnaire-collaboratif',
    titre: "Un dictionnaire collaboratif du nouchi voit le jour",
    chapo: "Un collectif de linguistes et de créateurs de contenu lance une plateforme pour documenter le parler des rues abidjanaises.",
    contenuHtml: '<p>Le projet, porté par une dizaine de contributeurs bénévoles, ambitionne de recenser plusieurs milliers d\'expressions nouchi avec leurs définitions et exemples d\'usage.</p>',
    tags: ['nouchi', 'langue', 'culture urbaine'],
    format: 'VIDEO_COURTE',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: 75,
    vuesTotal: 6700,
    publieLe: il(650),
    rubrique: r('culture'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Gomon', prenom: 'Edmond' },
  },
  {
    id: 'a8',
    slug: 'regions-korhogo-nouveau-marche-couvert',
    titre: 'Korhogo inaugure son nouveau marché couvert',
    chapo: "Attendue depuis trois ans, l'infrastructure doit désengorger le centre-ville et améliorer les conditions de travail de près de 2 000 commerçants.",
    contenuHtml: '<p>Les autorités locales ont procédé hier à l\'inauguration officielle du nouveau marché couvert de Korhogo, une infrastructure financée dans le cadre du programme national de modernisation des marchés.</p>',
    tags: ['korhogo', 'infrastructures'],
    format: 'EDITION',
    statut: 'PUBLIE',
    paywall: 'LIBRE',
    imageUneUrl: null,
    dureeEcouteSec: 110,
    vuesTotal: 2900,
    publieLe: il(900),
    rubrique: r('regions'),
    rubriquesSecondaires: [],
    medias: [],
    factCheck: null,
    auteur: { nom: 'Koré', prenom: 'Benjamin' },
  },
];

export const PRIX_VIE_CHERE = [
  { id: 'p1', produit: 'Riz (sac 50kg)', unite: 'sac', prix: 22500, variationPct: 1.8, dateReleve: il(200) },
  { id: 'p2', produit: 'Huile végétale', unite: 'litre', prix: 1450, variationPct: -0.5, dateReleve: il(200) },
  { id: 'p3', produit: 'Essence', unite: 'litre', prix: 890, variationPct: 0, dateReleve: il(200) },
  { id: 'p4', produit: 'Transport (Gbaka urbain)', unite: 'trajet', prix: 300, variationPct: 0, dateReleve: il(200) },
  { id: 'p5', produit: 'Gaz butane (12,5kg)', unite: 'bouteille', prix: 6000, variationPct: 2.4, dateReleve: il(200) },
];

export const EDITIONS = Array.from({ length: 6 }).map((_, i) => ({
  id: `e${i}`,
  numero: 7970 - i,
  dateParution: il((i + 1) * 1440),
  pdfUrl: '#',
  couvertureUrl: null,
  prix: 300,
}));

export const IS_FIXTURE_MODE_FLAG = 'notre-voie-fixture-mode';
